app/django_shop/blog/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', posts_list, name='posts_list_url'),
    path('post/<str:slug>/', PostDetail.as_view(), name='post_detail_url'),
    path('tag/<str:slug>', TagList.as_view(), name='tag_list_url'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/django_shop/django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from shop.models import Category

info_dict = {
    'queryset': Category.objects.all(),
}

urlpatterns = [
    path('smpgeoadmin/', admin.site.urls),
    path('', include('landing.urls')),
    path('services/', include('services.urls')),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('photogallery/', include('photogallery.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}}, name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/django_shop/blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.conf import settings
from django.utils.text import slugify
from transliterate import translit
from time import time
from django.urls import reverse

# Create your models here.

def gen_slug(title):
    try:
        new_slug = slugify(translit(title, reversed=True), allow_unicode=True)
    except:
        new_slug = slugify(title, allow_unicode=True)
    return new_slug + '-' + str(int(time()))


def image_folder(instance, filename):
    file_ext = filename.split('.')[1]
    filename = '{}.{}'.format(instance.slug, file_ext)
    return '{}/{}'.format(instance.slug, filename)


class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('tag_list_url', kwargs={'slug': self.slug})


class PostManager(models.Manager):
    def get_latest_posts(self):
        return self.all().reverse()[:2]


class Post(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    body = RichTextUploadingField()
    tags = models.ManyToManyField(Tag, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    meta_description = models.TextField(blank=True)
    meta_keywords = models.TextField(blank=True)
    image = models.ImageField(upload_to=image_folder, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post_detail_url', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['pub_date']

    objects = PostManager()

app/django_shop/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.core.paginator import Paginator
from django.views.generic import View


# Create your views here.


def posts_list(request):

    # get all posts
    posts = Post.objects.all()

    # break all posts to 10 posts on page with Paginator
    paginator = Paginator(posts, 10)

    # request current page and take it from paginator object
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    context = {
        'page': page,
    }
    return render(request, 'blog/posts_list.html', context=context)


class PostDetail(View):
    def get(self, request, slug):

        # request post by slug
        post = get_object_or_404(Post, slug=slug)
        return render(request, 'blog/post_detail.html', context={'post': post})

class TagList(View):
    def get(self, request, slug):

        # get tag by slug and get all posts by tag
        tag = get_object_or_404(Tag, slug=slug)
        return render(request, 'blog/tag_list.html', context={'tag': tag})

app/django_shop/blog/templates/blog/base_blog.html
{% extends 'base.html' %}

{% block title %}
Блог компании СМПГЕО
{% endblock %}

{% block maincontent %}


{% block content %}

{% endblock %}



{% endblock %}

app/django_shop/blog/templates/blog/post_detail.html
{% extends 'blog/base_blog.html' %}

{% block title %}
{{ post.title }} - {{ block.super }}
{% endblock %}

{% block content %}

<div class="card">
  <div class="card-header">
    <h3>{{ post.title }}</h3>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>{{ post.body|safe }}</p>
      <footer class="blockquote-footer">{{ post.author }}, <cite title="Source Title">{{ post.pub_date }}</cite></footer>
    </blockquote>
  </div>
  <div class="card-footer text-muted">
    Тэги:
    {% for tag in post.tags.all %}
      <a href="{{ tag.get_absolute_url }}">{{ tag }}</a>
    {% endfor %}
  </div>
</div>

{% endblock %}

app/django_shop/blog/templates/blog/posts_list.html
{% extends 'blog/base_blog.html' %}

{% block title %}
  {{ block.super }}
{% endblock %}

{% block content %}

<div class="alert alert-secondary mb-5" role="alert">
  <h2 class="">Блог компании СМПГЕО</h2>
</div>

{% for post in page %}
<div class="card text-center mb-3 shadow p-3 rounded">
  <a href="{{ post.get_absolute_url }}">
    <div class="post-image rounded" style="background-image: url('{{ MEDIA_URL }}{{ post.image.url }}');">
      <!-- <img class="card-img-top" src="{{ MEDIA_URL }}{{ post.image.url }}" alt="{{ post.title }}"> -->
    </div>
  </a>
  <div class="card-header rounded">
    <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
  </div>
  <div class="card-body rounded">
    <p class="card-text">{{ post.body|truncatewords:10|safe }}</p>
    <small class="text-muted">{{ post.pub_date }}</small>
    {% for tag in post.tags.all %}
      <a href="{{ tag.get_absolute_url }}">{{ tag }}</a>
    {% endfor %}
  </div>
</div>
<hr>
{% endfor %}

{% endblock %}

app/django_shop/blog/templates/blog/tag_list.html
{% extends 'blog/base_blog.html' %}

{% block title %}
  {{ block.super }}
{% endblock %}

{% block content %}

<h1 class="mb-5">Блог компании СМПГЕО</h1>
<h2 class="mb-5">Посты с тэгом {{ tag }}</h2>

{% for post in tag.post_set.all %}
<div class="card text-center mb-3 shadow p-3 rounded">
  <a href="{{ post.get_absolute_url }}">
    <div class="post-image rounded" style="background-image: url('{{ MEDIA_URL }}{{ post.image.url }}');">
      <!-- <img class="card-img-top" src="{{ MEDIA_URL }}{{ post.image.url }}" alt="{{ post.title }}"> -->
    </div>
  </a>
  <div class="card-header rounded">
    <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
  </div>
  <div class="card-body rounded">
    <p class="card-text">{{ post.body|truncatewords:10|safe }}</p>
    <small class="text-muted">{{ post.pub_date }}</small>
    {% for tag in post.tags.all %}
      <a href="{{ tag.get_absolute_url }}">{{ tag }}</a>
    {% endfor %}
  </div>
</div>
{% endfor %}

{% endblock %}