app/django_shop/blog/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', posts_list, name='posts_list_url'),
    path('post/<str:slug>/', PostDetail.as_view(), name='post_detail_url'),
    path('tag/<str:slug>', TagList.as_view(), name='tag_list_url'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/django_shop/django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from shop.models import Category

info_dict = {
    'queryset': Category.objects.all(),
}

urlpatterns = [
    path('smpgeoadmin/', admin.site.urls),
    path('', include('landing.urls')),
    path('services/', include('services.urls')),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('photogallery/', include('photogallery.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}}, name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/django_shop/shop/urls.py
from django.urls import path
from shop.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', shop_main, name='shop_main_url'),
    path('products/<str:slug>/', ProductDetail.as_view(), name='product_detail_url'),
    path('category/<str:slug>/', CategoryDetail.as_view(), name='category_detail_url'),
    path('cart/', cart, name='cart_url'),
    path('add_to_cart/', AddToCart.as_view(), name='add_to_cart_url'),
    path('delete_from_cart/', DeleteFromCart.as_view(), name='delete_from_cart_url'),
    path('change_item_qty/', ChangeItemQty.as_view(), name='change_item_qty_url'),
    path('make_order/', MakeOrder.as_view(), name='make_order_url'),
    path('order_success/', MakeOrder.as_view(), name='order_success_url'),
    path('account/', Account.as_view(), name='account_url'),
    path('registration/', Registration.as_view(), name='registration_url'),
    path('login/', Login.as_view(), name='login_url'),
    path('logout/', logout_user, name='logout_url'),
    path('password_reset/', PasswordReset.as_view(), name='password_reset_url'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/django_shop/shop/models.py
from __future__ import unicode_literals

from django.db import models
from time import time
from django.utils.text import slugify
from transliterate import translit
from django.urls import reverse
from django.conf import settings
from django.utils import timezone

from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
import random

# Create your models here.

def gen_slug(title):
    try:
        new_slug = slugify(translit(title, reversed=True), allow_unicode=True)
    except:
        new_slug = slugify(title, allow_unicode=True)
    return new_slug + '-' + str(int(time()))


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    meta_description = models.TextField(blank=True)
    meta_keywords = models.TextField(blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('category_detail_url', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['title']


class Brand(models.Model):
    title = models.CharField(max_length=100)
    meta_description = models.TextField(blank=True)
    meta_keywords = models.TextField(blank=True)
    def __str__(self):
        return self.title


def image_folder(instance, filename):
    file_ext = filename.split('.')[1]
    filename = '{}.{}'.format(instance.slug, file_ext)
    return '{}/{}'.format(instance.slug, filename)


class ProductManager(models.Manager):
    def get_random_three(self):
        return [random.choice(self.all()) for x in range(3)]



class Product(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, blank=True, unique=True)
    description = RichTextUploadingField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    available = models.BooleanField(default=True)
    meta_description = models.TextField(blank=True)
    meta_keywords = models.TextField(blank=True)

    class Meta:
        ordering = ['-price']


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product_detail_url', kwargs={'slug': self.slug})

    objects = ProductManager()


class SliderImage(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, blank=True, unique=True)
    image = models.ImageField(upload_to=image_folder)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)


class CartItem(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return 'Cart item for product {}'.format(self.product.title)

class Cart(models.Model):

    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

    def add_to_cart(self, request, slug):
        cart = self
        product = Product.objects.get(slug__iexact=slug)
        new_item = CartItem.objects.get_or_create(product=product, item_total=product.price)[0]
        if new_item not in cart.items.all():
            # так как метод .get_or_create возвращает кортеж, а объект CartItem там идет под нулевым индексом, именно его нам надо получить. Можно сделать двойное присваивание new_item, _ = ... , или можно забрать [0] от кортежа или от new_item
            cart.items.add(new_item)
            cart.save()

    # пересчет общей суммы в корзине
    def recount_cart(self):
        cart = self
        for item in cart.items.all():
            cart.cart_total += item.item_total
        return cart



ORDER_STATUS_CHOICES = (
    ('Принят в обработку', 'Принят в обработку'),
    ('Выполняется', 'Выполняется'),
    ('Оплачен', 'Оплачен'),
    ('Отгружен', 'Отгружен')
)

ORDER_BUYING_TYPE = (
    ('Самовывоз', 'Самовывоз'),
    ('Доставка', 'Доставка')
)

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    items = models.ForeignKey(Cart, on_delete=models.CASCADE, blank=True)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20)
    email = models.EmailField(max_length=100, null=True)
    address = models.CharField(max_length=255, blank=True)
    buying_type = models.CharField(max_length=40, choices=ORDER_BUYING_TYPE, default='Доставка')
    date = models.DateTimeField(auto_now_add=True)
    delivery_date = models.DateField(default=timezone.now)
    comments = models.TextField(blank=True)
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])

    def __str__(self):
        return 'Заказ №{}'.format(self.id)

    def details(self):
        for item in self.items.items.all():
            print(item.product.title, item.qty)

# # making view for orders
# class OrderDetail(Order):
#     # enable proxy extends functionality withou creating table in database
#     proxy = True
#     verbose_name = 'Детали заказа'
#     verbose_name_plural = 'Детали заказа'

app/django_shop/shop/forms.py
from django import forms
from .models import *
from django.utils import timezone
from django.contrib.auth.models import User


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'first_name',
            'last_name',
            'phone',
            'email',
            'buying_type',
            'address',
            'delivery_date',
            'comments',
        ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Фамилия'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Телефон'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'E-mail'}),
            'buying_type': forms.Select(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Адрес доставки'}),
            'delivery_date': forms.SelectDateWidget(),
            'comments': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Комментарий к заказу'}),
        }

        help_texts = {
            'buying_type': 'Доставка или самовывоз?',
            'delivery_date': 'Время доставки согласовывается дополнительно',
            'email': 'Мы не передаем вашу почту третьим лицам'
        }


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'username',
            'password',
        ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваше имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваша фамилия'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваш email'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Придумайте логин'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Придумайте пароль'}),
        }


    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if not first_name:
            raise forms.ValidationError('Введите своё имя')
        return first_name


    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if not last_name:
            raise forms.ValidationError('Введите свою фамилию')
        return last_name


    def clean_username(self):
        username = self.cleaned_data['username']

        if User.objects.filter(username=username):
            raise forms.ValidationError('Пользователь с таким логином уже зарегистрирован, придумайте другой логин')

        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError('Пользователь с почтой "{}" уже зарегистрирован, проверьте свой почтовый ящик, там есть письмо с учетными данными'.format(email))
        return email


class LoginForm(forms.Form):
    username = forms.CharField(help_text='Введите ваш логин')
    password = forms.CharField(widget=forms.PasswordInput, help_text='Введите ваш пароль')

    username.widget.attrs.update({'class': 'form-control', 'placeholder': 'Ваш логин'})
    password.widget.attrs.update({'class': 'form-control', 'placeholder': 'Ваш пароль'})

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        if not User.objects.filter(username=username):
            raise forms.ValidationError('Пользователь "{}" не зарегистрирован'.format(username))

        user = User.objects.get(username=username)
        # base_password = User.objects.get(username=username).password

        if user and not user.check_password(password):
            raise forms.ValidationError('Неправильный пароль')
        return self.cleaned_data


class PasswordResetForm(forms.Form):
    email = forms.EmailField(help_text='Введите email, указанный при регистрации')

    email.widget.attrs.update({'class': 'form-control', 'placeholder': 'Ваш email'})

    def clean(self):
        email = self.cleaned_data['email']

        if not User.objects.filter(email=email):
            raise forms.ValidationError('Пользователь с адресом {} не найден'.format(email))

        return self.cleaned_data

app/django_shop/shop/templates/shop/account.html
{% extends 'shop/base_shop.html' %}

{% block title %}
  {{ user }} - {{ block.super }}
{% endblock %}

{% block content %}


<h3 class="text-center mb-5">Добро пожаловать в личный кабинет, {{ user }}</h3>

{% if orders %}

<h4 class="text-center"></h4>
<table class="table">
  <thead class="thead-light">
  <tr>
    <th scope="col">Номер заказа</th>
    <th scope="col">Дата</th>
    <th scope="col">Статус</th>
    <th scope="col">Стоимость</th>
    <th scope="col">Детали заказа</th>
  </tr>
  </thead>


  {% for order in orders %}
  <tbody>
  <tr>
    <td>{{ order.id }}</td>
    <td>{{ order.date }}</td>
    <td>{{ order.status }}</td>
    <td>{{ order.total }} ₽</td>
    <td><!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{ order.id }}">
    Детали заказа №{{ order.id }}
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal-{{ order.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Заказ №{{ order.id }}</h5>
          <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button> -->
        </div>
        <div class="modal-body">
          <h4>Товар</h4>
            <table>
            {% for order_item in order.items.items.all %}

              <tr>
                <td>{{ order_item.product.title }}</td>
                <td>{{ order_item.qty }} шт</td>
                <td>{{ order_item.item_total }} ₽</td>
              </tr>
            {% endfor %}
              <tr>
                <td></td>
                <td>Итого</td>
                <td>{{ order.total }} ₽</td>
              </tr>
          </table>
          <h4>Заказчик</h4>
            <p>Имя: {{ order.first_name }}</p>
            <p>Фамилия: {{ order.last_name }}</p>
            <p>Телефон: {{ order.phone }}</p>
          <h4>Тип доставки</h4>
            <p>{{ order.buying_type }}</p>
            <p>{{ order.address }}</p>
          <h4>Комментарии к заказу</h4>
            <p>{{ order.comments }}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
          <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
        </div>
      </div>
    </div>
    </div></td>
    <td></td>
  </tr>
{% endfor %}
</tbody>
</table>


{% else %}
  <h3 class="text-center">У вас пока нет заказов</h3>
{% endif %}


{% endblock %}

app/django_shop/shop/templates/shop/base_shop.html
{% extends 'base.html' %}

{% block maincontent %}

<div class="alert alert-secondary mb-5" role="alert">
  <h2>Магазин</h2>
</div>
<!-- Navigation -->
{% include 'shop/includes/navbar.html' %}

{% block content %}
{% endblock %}

{% endblock %}

app/django_shop/shop/templates/shop/cart.html
{% extends 'shop/base_shop.html' %}
{% load static %}
{% block title %}

Корзина - {{ block.super }}

{% endblock %}

{% block content %}

<h2 class="mb-5">Ваша корзина</h2>

  <div class='cart-empty'></div>
{% if cart.items.count == 0 %}
  <h4>Корзина пуста</h4>
{% else %}
  <div class="my-cart">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Товар</th>
        <th scope="col">Количество</th>
        <th scope="col">Цена</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart.items.all %}
      <tr class='cart-item-{{ item.product.slug }}'>
        <input type="hidden" class="cart-item" data-slug="{{ item.product.slug }}">
        <td><a href="{{item.product.get_absolute_url}}">{{item.product.title}}</a></td>
        <td>
          <form action="" method="GET">
            <input class="cart-item-qty" data-id="{{ item.id }}" type="number" name="qty" value="{{item.qty}}" min="1">
          </form>
        </td>
        <td id="cart-item-total-{{ item.id }}">{{item.item_total}} ₽</td>
        <td><a href="#" class="remove-from-cart btn btn-danger" data-slug="{{ item.product.slug }}">Удалить</a></td>
      </tr>
      {% endfor %}
      <tr>
        <td></td>
        <td></td>
        <td class="cart-total-count" data-total="{{ cart.cart_total }}"><strong>{{ cart.cart_total }} ₽</strong></td>
        <td></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><a href="{% url 'make_order_url' %}" class="btn btn-info">Оформить заказ</a></td>
      </tr>
    </tbody>
  </table>
  </div>
{% endif %}



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script type="text/javascript">window.jQuery || document.write('<script type="text/javascript" src="{% static 'js/vendor/jquery/jquery.min.js' %}"><\/script>');</script>
<!-- <script src="{% static 'js/vendor/jquery/jquery.min.js' %}"></script> -->
<script>
  $(document).ready(function(){
    $(document).on('click', '.remove-from-cart', function(e){
      e.preventDefault()
      slug = $(this).attr('data-slug')
      data = {
        slug: slug,
      }
      console.log(data)
      $.ajax({
        type: "GET",
        url: "{% url 'delete_from_cart_url' %}",
        data: data,
        success: function(data){
          $('#cart-count').html(data.cart_items_count)
          $('.cart-total-count').html(data.cart_total)
          $('.cart-item-'+slug).remove()
          if(parseInt(data.cart_items_count) == 0){
            $('.cart-empty').append('<h4>Корзина пуста</4>')
            $('.my-cart').remove()
          }
        }
      })
    })
  })
  $(document).ready(function(){
    $(document).on('click', '.cart-item-qty', function(e){
      e.preventDefault()
      qty = $(this).val()
      item_id = $(this).attr('data-id')
      cart_total = $(this).attr('data-cart-total')
      data = {
        qty: qty,
        item_id: item_id,
        cart_total: cart_total
      }
      console.log(data.cart_total)
      $.ajax({
        type: "GET",
        url: '{% url "change_item_qty_url" %}',
        data: data,
        success: function(data){
          $('#cart-item-total-'+item_id).html(parseFloat(data.item_total).toFixed(2) + ' ₽')
          $('.cart-total-count').html(data.cart_total)
        }
      })
    })
  })
</script>
{% endblock %}

app/django_shop/shop/templates/shop/category_detail.html
{% extends 'shop/base_shop.html' %}
{% load static %}

{% block title %}
  Интернет-магазин измерительного оборудования для геодезистов - {{ block.super }}
{% endblock %}

{% block content %}

<div class="row">

  {% include 'shop/includes/categories.html' %}
  <!-- /.col-lg-3 -->

  <div class="col-lg-9">



<!-- Page Content -->


    {% include 'shop/includes/slider.html' %}

    {% include 'shop/includes/showcase.html' %}

  </div>
  </div>



{% endblock %}

app/django_shop/shop/templates/shop/delete_from_cart.html
{% extends 'shop/base_shop.html' %}

{% block title %}
  Удаление {{ item.product.title }} из корзины - {{ block.super }}
{% endblock %}

{% block content %}
<form class="mb-5" action="{% url 'delete_from_cart_url' slug=item.product.slug %}" method="post">
  {% csrf_token %}
  <h3 class="mb-5">Удалить {{ item.product.title }} из корзины?</h3>
  <a href="{% url 'cart_url' %}" class="btn btn-success">Не удалять</a>
  <button type="submit" class="btn btn-danger">Удалить</button>
</form>


{% endblock %}

app/django_shop/shop/templates/shop/login.html
{% extends 'shop/base_shop.html' %}

{% block title %}

Регистрация - {{ block.super }}

{% endblock %}

{% block content %}

<h2 class="text-center">Вход</h2>

{% if messages %}
{% for message in messages %}
  <h4 class="text-center">{{ message }}</h4>
{% endfor %}
{% endif %}
<form action="{% url 'login_url' %}" method="post">
  {% csrf_token %}

  {% for field in form %}

    {% if field.errors %}
      <div class="alert alert-danger">
        {{ field.errors }}
      </div>
    {% endif %}
    <div class="form-group">
      {{ field }}
      {% if field.help_text %}
        <small class="form-text text-muted">
          {{ field.help_text }}
        </small>
      {% endif %}
    </div>
  {% endfor %}
  <small class="form-text text-muted">
    <a href="{% url 'password_reset_url' %}">Восстановить пароль?</a>
  </small>
  <br>
  <button type="submit" class="btn btn-success btn-block">Войти</button>
</form>

{% endblock %}

app/django_shop/shop/templates/shop/make_order.html
{% extends 'shop/base_shop.html' %}

{% load static %}

{% block content %}

<h2 class="text-center mb-5">Оформление заказа</h2>

<div class="my-cart">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Товар</th>
      <th scope="col">Количество</th>
      <th scope="col">Цена</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.items.all %}
    <tr>
      <td><a href="{{item.product.get_absolute_url}}">{{ item.product.title }}</a></td>
      <td><p>{{ item.qty }}</p></td>
      <td>{{ item.item_total }} ₽</td>
    </tr>
    {% endfor %}
    <tr>
      <td></td>
      <td>Итого:</td>
      <td><strong>{{ cart.cart_total }} ₽</strong></td>
      <td></td>
    </tr>
  </tbody>
</table>
</div>


<h6 class="mb-4">Все поля, кроме комметария, обязательно нужно заполнить</h6>

<form method="post" action="{% url 'order_success_url' %}">
  {% csrf_token %}
  {% for field in form %}
    {% if field.errors %}
    <div class="alert alert-danger">
      {{ field.errors }}
    </div>
    {% endif %}
    <div class="form-group">
      {{ field }}
      {% if field.help_text %}
        <small class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn-success">Заказать</button>
</form>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script type="text/javascript">window.jQuery || document.write('<script type="text/javascript" src="{% static 'js/vendor/jquery/jquery.min.js' %}"><\/script>');</script>
<!-- <script src="{% static 'js/vendor/jquery/jquery.min.js' %}"></script> -->
<script>
  $(document).ready(function(){
    $(document).on('click', 'option', function(e){
      address = $('#id_address')
      value = $(this).val()
      if (value === 'Самовывоз'){
        address.prop('readonly', true)
      }
      else {
        address.prop('readonly', false)
      }
    })
  })
</script>




{% endblock %}

app/django_shop/shop/templates/shop/order_mail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div>
      <h2>Заказ №{{ order.id }}</h2>
      <hr>
      <h4>Товар</h4>
        <table>
        {% for order_item in order.items.items.all %}

          <tr>
            <td>{{ order_item.product.title }}</td>
            <td>{{ order_item.qty }} шт</td>
            <td>{{ order_item.item_total }} ₽</td>
          </tr>
        {% endfor %}
          <tr>
            <td></td>
            <td>Итого</td>
            <td>{{ order.total }} ₽</td>
          </tr>
      </table>
      <h4>Заказчик</h4>
        <p>Имя: {{ order.first_name }}</p>
        <p>Фамилия: {{ order.last_name }}</p>
        <p>Телефон: {{ order.phone }}</p>
      <h4>Тип доставки</h4>
        <p>{{ order.buying_type }}</p>
        <p>{{ order.address }}</p>
      <h4>Комментарии к заказу</h4>
        <p>{{ order.comments }}</p>
    </div>
  </body>
</html>

app/django_shop/shop/templates/shop/order_success.html
{% extends 'shop/base_shop.html' %}

{% block title %}
  Заказ №{{ order.id }} - {{ block.super }}
{% endblock %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Успех!</h1>
  <p class="lead">Ваш заказ №{{ order.id }} на сумму {{ order.total }} ₽ поступил в работу</p>
  <hr class="my-4">
  <p>Спасибо за заказ</p>
  <a class="btn btn-success btn-lg" href="{% url 'shop_main_url' %}" role="button">В магазин</a>
</div>
{% endblock %}

app/django_shop/shop/templates/shop/password_reset.html
{% extends 'shop/base_shop.html' %}

{% block content %}

<h3 class="text-center">Сброс пароля</h3>
<form class="" action="{% url 'password_reset_url' %}" method="post">
  {% csrf_token %}
  {% for field in form %}
    {% if field.errors %}
      <div class="alert alert-warning">
        {{ field.errors }}
      </div>
    {% endif %}

    {{ field }}
    <small class="form-text text-muted">
      {{ field.help_text }}
    </small>

  {% endfor %}
  <br>
  <button type="submit" class="btn btn-success">Сбросить пароль</button>
</form>
{% endblock %}

app/django_shop/shop/templates/shop/reg_mail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Интернет-магазин СМПГЕО</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <h3>Ваши учетные данные в магазине СМПГЕО</h3>
    <td bgcolor="#ffffff" style="padding: 40px 30px 40px 30px;">
 <table border="1" cellpadding="0" cellspacing="0" width="100%">
  <tr>
   <td>
    Логин
   </td>
   <td>
    {{ username }}
   </td>
  </tr>
  <tr>
   <td>
    Пароль
   </td>
   <td>
    {{ password }}
   </td>
  </tr>
  </body>
</html>

app/django_shop/shop/templates/shop/registration.html
{% extends 'shop/base_shop.html' %}

{% block title %}

Регистрация - {{ block.super }}

{% endblock %}

{% block content %}


<h2>Регистрация в интернет-магазине SMPGEO.RU</h2>

<form class="" action="{% url 'registration_url' %}" method="POST">
  {% csrf_token %}

  {% for field in form %}

    {% if field.errors %}
      <div class="alert alert-danger">
        {{ field.errors }}
      </div>
    {% endif %}
    <div class="form-group">
      {% if field.name == 'password_check' %}
        {{ field.label }}
      {% endif %}
      {{ field }}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn-success">Подтвердить</button>
</form>


{% endblock %}